### ISSUE TITLE
Add an overload to the `exec` method with `_Executable` statement for update and delete statements

### ISSUE THREAD

**Issue by joachimhuet** [fastapi/sqlmodel#909]
I think we should add an overload to the `exec` method to still have the possibility of passing an `_Executable` statement:

```
    @overload
    def exec(
        self,
        statement: _Executable,
        *,
        params: Optional[Union[Mapping[str, Any], Sequence[Mapping[str, Any]]]] = None,
        execution_options: Mapping[str, Any] = util.EMPTY_DICT,
        bind_arguments: Optional[Dict[str, Any]] = None,
        _parent_execute_state: Optional[Any] = None,
        _add_event: Optional[Any] = None,
    ) -> TupleResult[_TSelectParam]:
        ...

```

_Originally posted by @joachimhuet in https://github.com/tiangolo/sqlmodel/discussions/831#discussioncomment-9234181_

**Comment by federicober** [comment]
This is also valid for insert statements

**Comment by viaSeunghyun** [comment]
I agree.

The exec() method of Session allows Executable as a parameter for the statement, as shown in the code block below. 

Yes, Session's method exec has Executable as its type.
```
class Session(_Session):
    def exec(
        self,
        statement: Union[
            Select[_TSelectParam],
            SelectOfScalar[_TSelectParam],
            Executable[_TSelectParam],
        ],
        *,
        params: Optional[Union[Mapping[str, Any], Sequence[Mapping[str, Any]]]] = None,
        execution_options: Mapping[str, Any] = util.EMPTY_DICT,
        bind_arguments: Optional[Dict[str, Any]] = None,
        _parent_execute_state: Optional[Any] = None,
        _add_event: Optional[Any] = None,
    ) -> Union[TupleResult[_TSelectParam], ScalarResult[_TSelectParam]]:
```

When using direct SQL statements, especially when preparing user input, it needs to be wrapped with the text() function.
The text() function returns a TextClause, which inherits from Executable through multiple inheritance.

To **safely** perform SQL queries, you need to wrap them in `text()`,
```
@_document_text_coercion("text", ":func:`.text`", ":paramref:`.text.text`")
def text(text: str) -> TextClause:
```

```
class TextClause(
    roles.DDLConstraintColumnRole,
    roles.DDLExpressionRole,
    roles.StatementOptionRole,
    roles.WhereHavingRole,
    roles.OrderByRole,
    roles.FromClauseRole,
    roles.SelectStatementRole,
    roles.InElementRole,
    Generative,
    Executable,
    DQLDMLClauseElement,
    roles.BinaryElementRole[Any],
    inspection.Inspectable["TextClause"],
):
```

However, the problem arises because Executable is missing from the overload in Session.
I also received a deprecated warning and tried to transition, but most situations where I use execute are not Select statements. Therefore, I believe it's a fundamental error to not allow all types of SQL statements, starting from the deprecated warning.

In other words, at least in the 0.110 version I tested, it's clearly a bad idea to display a `deprecated` warning when calling the execute() method.

If only select statements are allowed, execute and exec should be considered as functions with different characteristics.
This inconsistency causes issues when working with non-Select SQL statements and limits the functionality of the Session.exec() method. It also creates confusion for users trying to follow best practices and handle deprecation warnings appropriately.

**Steps to Reproduce:**
1. Attempt to use Session.exec() with a non-Select SQL statement wrapped in text().
2. Observe the error or unexpected behavior.

**Expected Behavior:**
Session.exec() should accept all types of SQL statements wrapped in text(), as TextClause inherits from Executable.

**Actual Behavior:**
Session.exec() fails or produces unexpected results with non-Select SQL statements, despite them being valid Executable objects.

I've been checking and testing this and it does indeed output an error.
* Exception Type: AttributeError
* Exception.e: 'Session' object has no attribute 'exec'

**Additional Notes:**
This issue not only affects current usage but also complicates the transition process for users responding to deprecation warnings. It's important to maintain consistency in function behavior and support for different SQL statement types.

**Comment by sandangel** [comment]
I run into this issue to. Do we have any update?

**Comment by viaSeunghyun** [comment]
@sandangel 
Unofficially, don't use exec, ignore the warning, use execute. 
This is the cleanest way to do it without customising the FastAPI, otherwise a new @overload would need to be added in the new version.

**Comment by jtseven** [comment]
> @sandangel Unofficially, don't use exec, ignore the warning, use execute. This is the cleanest way to do it without customising the FastAPI, otherwise a new `@overload` would need to be added in the new version.

But `execute` is marked as deprecated by the type checker. It says:

> You probably want to use session.exec() instead of session.execute().
>
> This is the original SQLAlchemy session.execute() method that returns objects of type Row, and that you have to call scalars() to get the model objects.

**Comment by Blue9** [comment]
One workaround is to use `session.connection().execute(statement)`. This avoids the deprecation warning by explicitly dropping down to SQLAlchemy and is ultimately what SQLAlchemy's `session.execute(statement)` uses under the hood ([link](https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_35/lib/sqlalchemy/orm/session.py#L2256)). This shares the session transaction so you can mix this with other operations, and you will still have to call `session.commit()` or `session.rollback()` at the end of your transaction.

This could also cause the local ORM state to be stale so just be wary to refresh relevant ORM objects if you need to use them. Also, if you need to pass in custom options there are some discrepancies between the `Session.execute` and `Connection.execute` APIs.

**Comment by sandangel** [comment]
I just use the sqlalchemy AsyncSession and use `session.scalar` or `session.scalars` instead. We don't need to modify AsyncSession of sqlmodel.

**Comment by ddahan** [comment]
These workarounds falling back to raw SQLAlchemy instead of SQLModel feel clunky and confusing to me.
I'm not sure to understand the real reason of why it is impossible to write this code without having a warning?

```python
def delete_bulk_objects(model: type[T], conditions: list[Any], session: Session):
    statement = delete(model).where(*conditions)
    session.exec(statement)  # without type: ignore, it shows the 'session.exec(statement)' error.
    session.commit()
```

**Comment by vanakema** [comment]
I'm kind of confused as to why there's so much discussion about working around this using unwrapped sqlalchemy. Calling `exec` DOES work in my experience for these situations. It just fails the type checker because it's missing the overload. 

Am I missing something? If not, why isn't it just added as another overload?

**Comment by chriscarrollsmith** [comment]
Can confirm that exec works, but raises mypy errors:

```
tests/conftest.py:48: error: No overload variant of "exec" of "Session" matches argument type "Delete"  [call-overload]
tests/conftest.py:48: note: Possible overload variants:
tests/conftest.py:48: note:     def [_TSelectParam: Any] exec(self, statement: Select[_TSelectParam], *, params: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None = ..., execution_options: Mapping[str, Any] = ..., bind_arguments: dict[str, Any] | None = ..., _parent_execute_state: Any | None = ..., _add_event: Any | None = ...) -> TupleResult[_TSelectParam]
tests/conftest.py:48: note:     def [_TSelectParam: Any] exec(self, statement: SelectOfScalar[_TSelectParam], *, params: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None = ..., execution_options: Mapping[str, Any] = ..., bind_arguments: dict[str, Any] | None = ..., _parent_execute_state: Any | None = ..., _add_event: Any | None = ...) -> ScalarResult[_TSelectParam]
tests/conftest.py:49: error: No overload variant of "exec" of "Session" matches argument type "Delete"  [call-overload]
tests/conftest.py:49: note: Possible overload variants:
tests/conftest.py:49: note:     def [_TSelectParam: Any] exec(self, statement: Select[_TSelectParam], *, params: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None = ..., execution_options: Mapping[str, Any] = ..., bind_arguments: dict[str, Any] | None = ..., _parent_execute_state: Any | None = ..., _add_event: Any | None = ...) -> TupleResult[_TSelectParam]
tests/conftest.py:49: note:     def [_TSelectParam: Any] exec(self, statement: SelectOfScalar[_TSelectParam], *, params: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None = ..., execution_options: Mapping[str, Any] = ..., bind_arguments: dict[str, Any] | None = ..., _parent_execute_state: Any | None = ..., _add_event: Any | None = ...) -> ScalarResult[_TSelectParam]
Found 2 errors in 1 file (checked 14 source files)
```

**Comment by seriaati** [comment]
I did the following according to [the documentation](https://sqlmodel.tiangolo.com/tutorial/where/?h=col%28#type-annotations-and-errors) and there are no more type errors.

Original code:
```py
stmt = delete(EmailVerification).where(
    EmailVerification.user_id == user.id, EmailVerification.verified == False
)
```

Modified code:
```py
from sqlmodel import col

stmt = delete(EmailVerification).where(
    col(EmailVerification.user_id) == user.id, col(EmailVerification.verified) == False
)
```

**Comment by gaardhus** [comment]
@seriaati I tried updating my code to implement the `col()`, which does remove the type error for the definition, however not when executing the statement with `session.exec(stmt)`.

**Comment by vanakema** [comment]
Yea it's still an issue. Adding `col(...)` does not help with the typings problem that this issue is referring to, which is that there are type errors when passing the statement to `session.exec()`.

I too get the same issue that @gaardhus sees when they tried adding `col(...)`

**Comment by seriaati** [comment]
Sorry, didn't realize that there was another typing error with the statement itself.
I tried to fix this error in https://github.com/fastapi/sqlmodel/pull/1342, feedback is welcomed!

**Comment by the-vindicar** [comment]
Well, it's still broken for `delete`.
```python
    async with dbsession_factory() as session:
        stmt = delete(ModelClassName).where(col(ModelClassName.column_name) == some_value)
        # I still need to add 'type: ignore' here to silence mypy. Not very fond of this.
        await session.exec(stmt)  # type: ignore
        await session.commit()
```
I also noticed that `exec()` accepts `Executable[_TSelectParam]` instead of just `Executable`. Could this be the reason?

**Comment by seriaati** [comment]
@the-vindicar 
If you apply my patch in #1342 (or use my [fork](https://github.com/seriaati/sqlmodel/tree/main)), you won't see any typing errors.

**Comment by Aydin-ab** [comment]
Why is it not fixed already, it's just adding an overload, why is it taking more than a year, what is going on ?!

**Comment by vanakema** [comment]
> Why is it not fixed already, it's just adding an overload, why is it taking more than a year, what is going on ?!

The bystander effect 😁

**Comment by seriaati** [comment]
> Why is it not fixed already, it's just adding an overload, why is it taking more than a year, what is going on ?!

I had the exact same question when I was looking at this issue. This is why I decided to take action 😅

**Comment by Aydin-ab** [comment]
@seriaati  Lisan al Gaib !! 🙏

**Comment by vanakema** [comment]
> [@seriaati](https://github.com/seriaati) Lisan al Gaib !! 🙏

@seriaati take us to the promised land where there are no false linting errors 🙏

**Comment by sglbl** [comment]
Pyright also complains:
`/home/sglbl/sg_project_template/src/infra/postgres/database.py:32:15 -`
`error: No overloads for "exec" match the provided arguments (reportCallIssue)`

**Comment by tiangolo** [comment]
This should be solved by https://github.com/fastapi/sqlmodel/pull/1342, available in SQLModel version 0.0.25, released in the next few hours. 🎉

**Comment by Vigilans** [comment]
Issue in https://github.com/fastapi/sqlmodel/issues/376 seems not fixed actually? There is still no overload for text() clause.

**Comment by putradimas** [comment]
I'm using version 0.0.38 and the overload of exec for text still doesn't exist.

> No overloads for "exec" match the provided arguments - Pylance[[reportCallIssue](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportCallIssue.md)]

**Comment by YuriiMotov** [comment]
> I'm using version 0.0.38 and the overload of exec for text still doesn't exist.

See https://github.com/fastapi/sqlmodel/pull/1657
